[package]
name = "my_mat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_arr_math = {path = "/home/mr_platypus/Documents/Code/Rust-Projects/libs/my_arr_math"}
